### ISSUE TITLE
Enhance Travis CI setting

### ISSUE THREAD

**Issue by peter279k** [Swop/github-webhook-security-checker#2]
According to this official [blog post](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment), the default dist on Travis CI build environment has changed into `xenial`.

And it will be failed on `php-5.x` versions during Travis CI build.

To resolve this issue, some suggestions I recommend are as follows:

- Dropping these `php-5.x` versions and let this package require stable `php-7.1` version at least.
And it will avoid this issue directly.
- Define the `matrix` setting to define the `dist: trusty` for these `php-5.x` versions during Travis CI build.

**Comment by Swop** [comment]
@peter279k Sorry for the (long) delay.

I've pushed a v3.0 today (which drop support for older php versions < 7.2), and switched to GitHub Actions instead of Travis.
Thanks for the notice.

**Comment by peter279k** [comment]
Thanks for your reply.

I will look at other improvements :).
